# sonar-project.properties
sonar.projectKey=AryanAssis_ENGS2
sonar.organization=aryanassis
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13
